### ISSUE TITLE
More info in console mode

### ISSUE THREAD

**Issue by vaut** [maxsupermanhd/WMT#1]
1) author maps
2) license maps
3) oil on maps and oil per player
4) mods

**Comment by maxsupermanhd** [comment]
Authors, where, when and license added on `5d165fa25d4fcb95cb02ecc3498dd3a071ec8b3e`
oil was added for a long time (since drawing on previews).
Printing info to console added in `83e7d48a8cd4ac7ee28d5a2626272049c304cb44` and few commits earlier.
Mod detecting-removing-manipulating will be added soon.
Also there will be 1.4 release soon with all that stuff available.

**Comment by vaut** [comment]
thanks
